
package ihm;


import net.objecthunter.exp4j.Expression;
import net.objecthunter.exp4j.ExpressionBuilder;
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butDel = new javax.swing.JButton();
        butC = new javax.swing.JButton();
        butR = new javax.swing.JButton();
        butL = new javax.swing.JButton();
        butMul = new javax.swing.JButton();
        but9 = new javax.swing.JButton();
        but8 = new javax.swing.JButton();
        but7 = new javax.swing.JButton();
        butMin = new javax.swing.JButton();
        but5 = new javax.swing.JButton();
        but4 = new javax.swing.JButton();
        but6 = new javax.swing.JButton();
        but1 = new javax.swing.JButton();
        but2 = new javax.swing.JButton();
        but3 = new javax.swing.JButton();
        butP = new javax.swing.JButton();
        butD = new javax.swing.JButton();
        butZ = new javax.swing.JButton();
        butDot = new javax.swing.JButton();
        butEq = new javax.swing.JButton();
        procLab = new javax.swing.JTextField();
        resLab = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        butDel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        butDel.setForeground(new java.awt.Color(255, 204, 0));
        butDel.setText("del");
        butDel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butDelMouseClicked(evt);
            }
        });

        butC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        butC.setForeground(new java.awt.Color(255, 0, 0));
        butC.setText("C");
        butC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butCMouseClicked(evt);
            }
        });

        butR.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        butR.setText(")");
        butR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butRMouseClicked(evt);
            }
        });
        butR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butRActionPerformed(evt);
            }
        });

        butL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        butL.setText("(");
        butL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butLMouseClicked(evt);
            }
        });
        butL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butLActionPerformed(evt);
            }
        });

        butMul.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        butMul.setText("x");
        butMul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butMulMouseClicked(evt);
            }
        });

        but9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        but9.setText("9");
        but9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                but9MouseClicked(evt);
            }
        });

        but8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        but8.setText("8");
        but8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                but8MouseClicked(evt);
            }
        });

        but7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        but7.setText("7");
        but7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                but7MouseClicked(evt);
            }
        });

        butMin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        butMin.setText("-");
        butMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butMinMouseClicked(evt);
            }
        });

        but5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        but5.setText("5");
        but5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                but5MouseClicked(evt);
            }
        });

        but4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        but4.setText("4");
        but4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                but4MouseClicked(evt);
            }
        });

        but6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        but6.setText("6");
        but6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                but6MouseClicked(evt);
            }
        });

        but1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        but1.setText("1");
        but1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                but1MouseClicked(evt);
            }
        });

        but2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        but2.setText("2");
        but2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                but2MouseClicked(evt);
            }
        });

        but3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        but3.setText("3");
        but3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                but3MouseClicked(evt);
            }
        });

        butP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        butP.setText("+");
        butP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butPMouseClicked(evt);
            }
        });

        butD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        butD.setText("/");
        butD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butDMouseClicked(evt);
            }
        });

        butZ.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        butZ.setText("0");
        butZ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butZMouseClicked(evt);
            }
        });

        butDot.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        butDot.setText(".");
        butDot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butDotMouseClicked(evt);
            }
        });

        butEq.setBackground(new java.awt.Color(0, 153, 255));
        butEq.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        butEq.setForeground(java.awt.Color.white);
        butEq.setText("=");
        butEq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butEqMouseClicked(evt);
            }
        });

        procLab.setEditable(false);
        procLab.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        procLab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procLabActionPerformed(evt);
            }
        });

        resLab.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        resLab.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        resLab.setAlignmentX(50.0F);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resLab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(procLab)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(butL, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(butR, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(butC, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(butDel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(but7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(but8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(but9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(butMul, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(but4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(but5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(but6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(butMin, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(but1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(but2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(but3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(butP, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(butD, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(butZ, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(butDot, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(butEq, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(procLab, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resLab, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butDel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butC, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butR, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butL, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butMul, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butMin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butP, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butEq, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butDot, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butZ, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butD, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butLActionPerformed

    private void procLabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procLabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_procLabActionPerformed

    private void butLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butLMouseClicked
        // TODO add your handling code here:
        String proc = procLab.getText();
        if(proc.length() != 0 )
            if(!proc.endsWith("+") && !proc.endsWith("-") && !proc.endsWith("x") && !proc.endsWith("/") && !proc.endsWith("("))
                return;
        procLab.setText(proc+"(");
    }//GEN-LAST:event_butLMouseClicked

    private void butRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butRMouseClicked
        // TODO add your handling code here:
        String proc = procLab.getText();
        procLab.setText(proc+")");
    }//GEN-LAST:event_butRMouseClicked

    private void butCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butCMouseClicked
        // TODO add your handling code here:
        
        procLab.setText("");
        resLab.setText("0");
    }//GEN-LAST:event_butCMouseClicked

    private void butRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butRActionPerformed

    private void butDelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butDelMouseClicked
        // TODO add your handling code here:
        String s = procLab.getText();
        String d = s.substring(0, s.length() - 1);
        procLab.setText(d);
    }//GEN-LAST:event_butDelMouseClicked

    private void but7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_but7MouseClicked
        // TODO add your handling code here:
         String proc = procLab.getText();
        procLab.setText(proc+"7");
    }//GEN-LAST:event_but7MouseClicked

    private void but8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_but8MouseClicked
        // TODO add your handling code here:
         String proc = procLab.getText();
        procLab.setText(proc+"8");
    }//GEN-LAST:event_but8MouseClicked

    private void but9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_but9MouseClicked
        // TODO add your handling code here:
         String proc = procLab.getText();
        procLab.setText(proc+"9");
    }//GEN-LAST:event_but9MouseClicked

    private void butMulMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butMulMouseClicked
        // TODO add your handling code here:
        
        String proc = procLab.getText();
       if(proc.endsWith("x")){
           return;
       }else{
           procLab.setText(proc+"x");
       }
    }//GEN-LAST:event_butMulMouseClicked

    private void but4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_but4MouseClicked
        // TODO add your handling code here:
         String proc = procLab.getText();
        procLab.setText(proc+"4");
    }//GEN-LAST:event_but4MouseClicked

    private void but5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_but5MouseClicked
        // TODO add your handling code here:
         String proc = procLab.getText();
        procLab.setText(proc+"5");
    }//GEN-LAST:event_but5MouseClicked

    private void but6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_but6MouseClicked
        // TODO add your handling code here:
         String proc = procLab.getText();
        procLab.setText(proc+"6");
    }//GEN-LAST:event_but6MouseClicked

    private void butMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butMinMouseClicked
        // TODO add your handling code here:
        String proc = procLab.getText();
        procLab.setText(proc+"-");
    }//GEN-LAST:event_butMinMouseClicked

    private void but1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_but1MouseClicked

         String proc = procLab.getText();
          procLab.setText(proc+"1");
    }//GEN-LAST:event_but1MouseClicked

    private void but2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_but2MouseClicked
        // TODO add your handling code here:
         String proc = procLab.getText();
        procLab.setText(proc+"2");
    }//GEN-LAST:event_but2MouseClicked

    private void but3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_but3MouseClicked
        // TODO add your handling code here:
         String proc = procLab.getText();
        procLab.setText(proc+"3");
    }//GEN-LAST:event_but3MouseClicked

    private void butPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butPMouseClicked
        // TODO add your handling code here:
        String proc = procLab.getText();
        procLab.setText(proc+"+");
    }//GEN-LAST:event_butPMouseClicked

    private void butEqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butEqMouseClicked
        // TODO add your handling code here:
        try {
            String rs = procLab.getText();
            double res = resultCal(rs);
            resLab.setText(res+"");
        } catch (Exception e) {
            resLab.setText(e+"");
        }
    }//GEN-LAST:event_butEqMouseClicked

    private void butDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butDMouseClicked
        // TODO add your handling code here:
        String proc = procLab.getText();
       if(proc.endsWith("/")){
           return;
       }else{
           procLab.setText(proc+"/");
       }
    }//GEN-LAST:event_butDMouseClicked

    private void butZMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butZMouseClicked
        // TODO add your handling code here:
         String proc = procLab.getText();
        procLab.setText(proc+"0");
    }//GEN-LAST:event_butZMouseClicked

    private void butDotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butDotMouseClicked
        // TODO add your handling code here:
         String proc = procLab.getText();
       if(proc.endsWith(".")){
           return;
       }else{
           procLab.setText(proc+".");
       }
    }//GEN-LAST:event_butDotMouseClicked

    
    public double resultCal(String expression){
        double result = 0;
        try {
            Expression exp = new ExpressionBuilder(expression.replace("x", "*")).build();
            result = exp.evaluate();
        } catch (Exception e) {
            resLab.setText("Error");
        }
        return result;
    } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton but1;
    private javax.swing.JButton but2;
    private javax.swing.JButton but3;
    private javax.swing.JButton but4;
    private javax.swing.JButton but5;
    private javax.swing.JButton but6;
    private javax.swing.JButton but7;
    private javax.swing.JButton but8;
    private javax.swing.JButton but9;
    private javax.swing.JButton butC;
    private javax.swing.JButton butD;
    private javax.swing.JButton butDel;
    private javax.swing.JButton butDot;
    private javax.swing.JButton butEq;
    private javax.swing.JButton butL;
    private javax.swing.JButton butMin;
    private javax.swing.JButton butMul;
    private javax.swing.JButton butP;
    private javax.swing.JButton butR;
    private javax.swing.JButton butZ;
    private javax.swing.JTextField procLab;
    private javax.swing.JLabel resLab;
    // End of variables declaration//GEN-END:variables
}
